version: "3.9"
services:
  node:
    image: "node"
    ports:
      - "5000:5000"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: "npm run dev"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
